### ISSUE TITLE
Usage as a library?

### ISSUE THREAD

**Issue by themartorana** [maruel/panicparse#16] opened 2015-11-30 17:59 UTC
The documentation states: "Usable as a library!" But I can't figure out how to use this to get a string representation of the parsed output (without needing to use the `internal` package).

Is there a standard method I'm missing to get in an `io.Writer` the contents that would normally be printed to `stdout` or do I need to duplicate `internal` methods in my own code?

Thanks!

**Comment by maruel** [comment] 2015-11-30 18:15
Parsing is usable as a library. Writing is not.

The reason is that output is very application context dependent. There's issue #8 about exporting the writer which I think is a good idea but I haven't thought out the API yet. That's why in the meantime I've asked users to copy paste the subset of internal/main.go they need. The code is 100 lines.

The main issue with the writing part is that it intermingle coloring which is not necessarily appropriate everywhere. I think a great use case would be with a Go debugger but I really want to nail the API down before doing this, as you don't want to use color schemes that mess up with the debugger for example, and a GUI debugger needs different text representation than ANSI encoded. In the end, copying the 100 lines is not a big deal either IMHO.

I consider this a dupe of issue #8. Please reopen if you disagree or I misunderstood your request.

**Closed by maruel** 2015-11-30 18:15 UTC

**Comment by themartorana** [comment] 2015-11-30 18:31
Sounds good, thanks for the detailed explanation!
